// <auto-generated />
using System;
using ClinicaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ClinicaAPI.Migrations
{
    [DbContext(typeof(ClinicaContext))]
    [Migration("20250317172649_UpdateEntities")]
    partial class UpdateEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicaAPI.Models.Atendimento", b =>
                {
                    b.Property<int>("Id_Atendimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Atendimento"));

                    b.Property<int?>("Cpf_Dentista")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Cpf_Paciente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("Custo_Estimado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Data_Atendimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao_Atendimento")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Tipo_Procedimento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id_Atendimento");

                    b.HasIndex("Cpf_Dentista");

                    b.HasIndex("Cpf_Paciente");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("ClinicaAPI.Models.Clinica", b =>
                {
                    b.Property<string>("Cnpj_Clinica")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int?>("Id_Endereco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Id_Telefone")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Id_Usuario")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome_Clinica")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Cnpj_Clinica");

                    b.ToTable("Clinicas");
                });

            modelBuilder.Entity("ClinicaAPI.Models.Dentista", b =>
                {
                    b.Property<int>("Cpf_Dentista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cpf_Dentista"));

                    b.Property<int?>("Cnpj_Clinica")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Cro_Dentista")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("Data_Contratacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email_Dentista")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Especialidade")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Id_Endereco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Id_Telefone")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome_Dentista")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Cpf_Dentista");

                    b.ToTable("Dentistas");
                });

            modelBuilder.Entity("ClinicaAPI.Models.Endereco", b =>
                {
                    b.Property<int>("Id_Endereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Endereco"));

                    b.Property<string>("Bairro_Endereco")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Cep")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Cidade_Endereco")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Complemento_Endereco")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Estado_Endereco")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Numero_Endereco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Rua_Endereco")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id_Endereco");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("ClinicaAPI.Models.Paciente", b =>
                {
                    b.Property<int>("Cpf_Paciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cpf_Paciente"));

                    b.Property<int?>("Cnpj_Clinica")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("Data_Nascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Genero_Paciente")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Id_Endereco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Id_Telefone")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome_Paciente")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Cpf_Paciente");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ClinicaAPI.Models.Telefone", b =>
                {
                    b.Property<int>("Id_Telefone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Telefone"));

                    b.Property<string>("Numero_Telefone")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tipo_Telefone")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id_Telefone");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("ClinicaAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("Email_Usuario")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Senha_Usuario")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status_Usuario")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ClinicaAPI.Models.Atendimento", b =>
                {
                    b.HasOne("ClinicaAPI.Models.Dentista", "Dentista")
                        .WithMany()
                        .HasForeignKey("Cpf_Dentista");

                    b.HasOne("ClinicaAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("Cpf_Paciente");

                    b.Navigation("Dentista");

                    b.Navigation("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
